# Generated by Django 3.2.8 on 2022-04-03 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=50)),
                ('comment_time', models.DateField()),
                ('text', models.CharField(max_length=250)),
                ('stock_symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=50)),
                ('day', models.DateField()),
                ('volume', models.IntegerField()),
                ('stock_open', models.FloatField()),
                ('stock_high', models.FloatField()),
                ('stock_low', models.FloatField()),
                ('stock_close', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('stock_symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('isin', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('stock_list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stocks.datasource')),
            ],
        ),
    ]
