# Generated by Django 4.1 on 2022-10-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_datasource_stock_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='stock_symbol',
            field=models.CharField(max_length=50),
        ),
    ]
