# Generated by Django 4.1 on 2022-10-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_datasource_stock_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
