# Generated by Django 4.1 on 2022-10-09 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_stock_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='stock_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock'),
        ),
    ]
