# Generated by Django 4.1 on 2022-10-17 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_alter_datasource_stock_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='email',
        ),
    ]
