# Generated by Django 4.1 on 2022-12-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_remove_stock_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daylist',
            old_name='stock_list',
            new_name='stock_symbol',
        ),
        migrations.AddField(
            model_name='daylist',
            name='candle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='daylist',
            name='mean',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='daylist',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
