# Generated by Django 4.1 on 2022-12-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_rename_stock_list_daylist_stock_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daylist',
            name='volume',
            field=models.FloatField(null=True),
        ),
    ]
