# Generated by Django 4.1 on 2022-12-10 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_alter_daylist_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daylist',
            name='stock_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stocks.stock'),
        ),
    ]
