# Generated by Django 4.1 on 2022-12-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_alter_daylist_stock_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='daylist',
            name='option',
            field=models.CharField(choices=[('C', 'Candles'), ('M', 'Mean'), ('V', 'Volume')], max_length=1, null=True),
        ),
    ]
